# Generated by Django 3.1.7 on 2021-03-23 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210322_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 0, 20), verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='shortcode',
            name='shortcode',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP')], max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='psycho_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.shortcode'),
        ),
    ]
