# Generated by Django 3.1.7 on 2021-03-24 14:37

import datetime
from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210323_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 0, 20), verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True, verbose_name='Date of birthday in timestamp'),
        ),
    ]
