# Generated by Django 3.1.7 on 2021-03-30 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210330_1824'),
        ('users', '0004_auto_20210324_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 0, 20), verbose_name='Expires at'),
        ),
        migrations.CreateModel(
            name='UserContanctPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='User phone')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Rating grade')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Characterisric sender name')),
                ('reciever_name', models.CharField(default='1617117871.997034', max_length=100, verbose_name='Characterisric sender name')),
                ('compatible', models.BooleanField(default=False)),
                ('negative_sides', models.ManyToManyField(related_name='Characteristic_negative_sides', to='info.NegativeSide')),
                ('positive_sides', models.ManyToManyField(related_name='Characteristic_positive_sides', to='info.PositiveSide')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
