# Generated by Django 3.1.7 on 2021-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210405_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='reciever_name',
            field=models.CharField(default='1617602083.205247', max_length=100, verbose_name='Characterisric sender name'),
        ),
    ]
