# Generated by Django 3.1.7 on 2021-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210405_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_book_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='reciever_name',
            field=models.CharField(default='1617602316.69698', max_length=100, verbose_name='Characterisric sender name'),
        ),
    ]
