# Generated by Django 3.1.7 on 2021-04-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210405_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='reciever_name',
            field=models.CharField(default='1617604570.25847', max_length=100, verbose_name='Characterisric sender name'),
        ),
    ]
