# Generated by Django 3.1.7 on 2021-04-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210404_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='reciever_name',
            field=models.CharField(default='1617562675.491984', max_length=100, verbose_name='Characterisric sender name'),
        ),
    ]
