# Generated by Django 3.1.7 on 2021-03-19 08:53

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Сфера деятольности',
                'verbose_name_plural': 'Сферы деятольности',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='TalkThemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
                ('image_png', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='', verbose_name='ImagePNG')),
                ('image_svg', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='', verbose_name='ImagePNG')),
            ],
            options={
                'verbose_name': 'Темы для разговора',
                'verbose_name_plural': 'Темы для разговоров',
            },
        ),
    ]
