# Generated by Django 3.1.7 on 2021-03-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210330_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negativeside',
            options={'verbose_name': 'негативная сторона', 'verbose_name_plural': 'негативные стороны'},
        ),
        migrations.AlterModelOptions(
            name='positiveside',
            options={'verbose_name': 'позитивная сторона', 'verbose_name_plural': 'позитивные стороны'},
        ),
    ]
