# Generated by Django 3.1.7 on 2021-03-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210330_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkthemes',
            name='image_svg',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ImageSVG'),
        ),
    ]
