# Generated by Django 3.1.7 on 2021-04-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_merge_20210330_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkthemes',
            name='image_svg',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ImageSVG'),
        ),
    ]
